-- 최댓값 구하기
SELECT MAX(DATETIME) FROM ANIMAL_INS
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME DESC LIMIT 1

-- 최솟값 구하기
SELECT MIN(DATETIME) FROM ANIMAL_INS

-- 동물수 구하기
SELECT COUNT(ANIMAL_ID) FROM ANIMAL_INS

-- 중복 제거하기
SELECT COUNT(DISTINCT(NAME)) FROM ANIMAL_INS